### ISSUE TITLE
Navigation bar

### ISSUE THREAD

**Issue by geromegrignon** [this-is-learning/this-is-learning-conf-website#1]
Hi @santoshyadavdev, I propose you create something similar to the existing conf websites:

<img width="1442" alt="image" src="https://github.com/this-is-learning/this-is-learning-conf-website/assets/32737308/3b0a5215-ad2c-4970-abf8-12f290ac7f7a">

<img width="1457" alt="image" src="https://github.com/this-is-learning/this-is-learning-conf-website/assets/32737308/c7dae7cd-c149-4a9e-be7c-83244ac21d81">

So the following items:

- logo
- Agenda
- Speakers
- Sponsors
- About
- CoC
- Register (external link)

**Comment by santoshyadavdev** [comment]
We can borrow it from ngbelgrade thats the 2nd image right?

**Comment by santoshyadavdev** [comment]
We can have 

- logo
- Agenda
- Speakers - this will be enabled later, we can keep it hidden initially
- Sponsors
- CFP 
- About
- CoC
- Register (external link)

**Comment by santoshyadavdev** [comment]
![Screenshot_2024-02-09-19-33-43-79_572064f74bd5f9fa804b05334aa4f912.jpg](https://github.com/this-is-learning/this-is-learning-conf-website/assets/11923975/b5ce6afd-d02e-4039-abe0-57a451828ef7)

**Comment by tobySolutions** [comment]
Hello there, so I see that the navbar exists and we have a couple of pages to work on; I can pick up some pages and start work on them, but, I want to get some clarifications regarding what things will go into those pages and how we need them structured @santoshyadavdev, @geromegrignon 🙌 .

Thank you!

**Comment by geromegrignon** [comment]
I created a dedicated issue for each page so it'll be easier to talk in isolation for each topic.

**Comment by tobySolutions** [comment]
> I created a dedicated issue for each page so it'll be easier to talk in isolation for each topic.

Awesome! Thanks Gerome. Let me check those out.

**Comment by tobySolutions** [comment]
I think we need one for the homepage too, or do you want to handle it?

**Comment by geromegrignon** [comment]
Done

**Comment by tobySolutions** [comment]
Perfect, thanks! So sorry, but, one more thing actually; the "Register" button should take users to a Google form, right?

**Comment by geromegrignon** [comment]
A Google Form will be used for the CFP part.
For the registration It might depend on the platform used to broadcast the live event.

**Comment by tobySolutions** [comment]
> A Google Form will be used for the CFP part. For the registration It might depend on the platform used to broadcast the live event.

Hmm, oh ok thanks 🙌
