### ISSUE TITLE
[Page] Home

### ISSUE THREAD

**Issue by geromegrignon** [this-is-learning/this-is-learning-conf-website#8]
## Description

Placeholder to talk about the *Home** page.

**Comment by tobySolutions** [comment]
Hello there, @geromegrignon and @santoshyadavdev I would like to work on this. Is there a sample we have in mind that we want to follow? Assets we'll need or a specific structure the page must have?

**Comment by tobySolutions** [comment]
Please any updates regarding this?

**Comment by santoshyadavdev** [comment]
The registration link is : https://konfhub.com/tc-b34e332d 
@tobySolutions can you refer the homepage from https://angularbelgrade.org/

Dates are 16-17 May

**Comment by geromegrignon** [comment]
If it can save you some time, I started working on an open-source generic conf website: https://event-edge.gerome.dev/
codebase is here: https://github.com/EventEdge/EventEdge

**Comment by santoshyadavdev** [comment]
this is nice, so how we proceed with it, should we clone and use it?

**Comment by geromegrignon** [comment]
It could be just copied as with tailwind, most content is inside the page files themselves.

I'll let @tobySolutions adapt it to your needs.

**Comment by geromegrignon** [comment]
And as the registration is open, We might want to quickly deploy the home page, hiding the other links by now to get it started asap.

**Comment by santoshyadavdev** [comment]
Yeah sounds good to me 🤗

**Comment by tobySolutions** [comment]
> And as the registration is open, We might want to quickly deploy the home page, hiding the other links by now to get it started asap.

Sounds wonderful! I can get that out soon. Currently on it.

**Comment by tobySolutions** [comment]
I made a PR for this already #9
